<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_z7vsIGwQEe6CV7MUNvKj1Q" name="Project_Validation_Diagram_Obaydah_Bouifadene-Iliass_Dahman" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_z7vsIWwQEe6CV7MUNvKj1Q" name="Project_Validation_Process_Obaydah_Bouifadene-Iliass_Dahman">
      <elements xmi:type="process:Lane" xmi:id="_z7vsImwQEe6CV7MUNvKj1Q" name="Employee lane" actor="_z7wTMmwQEe6CV7MUNvKj1Q">
        <elements xmi:type="process:StartEvent" xmi:id="_z7vsI2wQEe6CV7MUNvKj1Q" name="Start1" outgoing="_z7vsOGwQEe6CV7MUNvKj1Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_z7vsJGwQEe6CV7MUNvKj1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_z7vsJWwQEe6CV7MUNvKj1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_z7vsJmwQEe6CV7MUNvKj1Q" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_z7vsJ2wQEe6CV7MUNvKj1Q" name="Approve proposal" outgoing="__k1s0GwpEe6kvqzAwC8jmg" incoming="_z7vsOGwQEe6CV7MUNvKj1Q" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_z7vsKGwQEe6CV7MUNvKj1Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_z7vsKWwQEe6CV7MUNvKj1Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_z7vsKmwQEe6CV7MUNvKj1Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_z7vsK2wQEe6CV7MUNvKj1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_z7vsLGwQEe6CV7MUNvKj1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_z7vsLWwQEe6CV7MUNvKj1Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_z7vsLmwQEe6CV7MUNvKj1Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_z7vsL2wQEe6CV7MUNvKj1Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_z7vsMGwQEe6CV7MUNvKj1Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_DmE4MGwrEe6kvqzAwC8jmg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_z7vsMmwQEe6CV7MUNvKj1Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_z7vsM2wQEe6CV7MUNvKj1Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_z7wJ0GwpEe6kvqzAwC8jmg" name="Notify proposal approved" outgoing="_S2dugGwqEe6kvqzAwC8jmg" incoming="_L7P98GwsEe6kvqzAwC8jmg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_z75TwWwpEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_z75TwGwpEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_z75TwmwpEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_z75Tw2wpEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_z75TxGwpEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_z75TxWwpEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_z75Tx2wpEe6kvqzAwC8jmg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_z75TxmwpEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_z75TyWwpEe6kvqzAwC8jmg">
            <targetForm xmi:type="expression:Expression" xmi:id="_DmE4MWwrEe6kvqzAwC8jmg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_z75TyGwpEe6kvqzAwC8jmg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_z75Ty2wpEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_GR3lgGwqEe6kvqzAwC8jmg" name="Analyze impact" outgoing="_TIwYYGwqEe6kvqzAwC8jmg" incoming="_S2dugGwqEe6kvqzAwC8jmg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GR3lgmwqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GR3lgWwqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GR3lg2wqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GR4MkGwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GR4MkWwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GR4MkmwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GR4MlGwqEe6kvqzAwC8jmg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GR4Mk2wqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_GR4MlmwqEe6kvqzAwC8jmg">
            <targetForm xmi:type="expression:Expression" xmi:id="_DmE4MmwrEe6kvqzAwC8jmg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_GR4MlWwqEe6kvqzAwC8jmg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_GR4MmGwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_H484EGwqEe6kvqzAwC8jmg" name="Validate project" outgoing="_TcVbsGwqEe6kvqzAwC8jmg" incoming="_TIwYYGwqEe6kvqzAwC8jmg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_H484EmwqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_H484EWwqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_H484E2wqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_H484FGwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_H484FWwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_H484FmwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_H49fIWwqEe6kvqzAwC8jmg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_H49fIGwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_H49fI2wqEe6kvqzAwC8jmg">
            <targetForm xmi:type="expression:Expression" xmi:id="_DmE4M2wrEe6kvqzAwC8jmg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_H49fImwqEe6kvqzAwC8jmg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_H49fJWwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_JRzhYGwqEe6kvqzAwC8jmg" name="Notify project accepted" outgoing="_T4ZsoGwqEe6kvqzAwC8jmg" incoming="_zUq0UGwsEe6kvqzAwC8jmg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JRzhYmwqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JRzhYWwqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JRzhY2wqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_JRzhZGwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_JRzhZWwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_JRzhZmwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_JRzhaGwqEe6kvqzAwC8jmg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_JRzhZ2wqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_JRzhamwqEe6kvqzAwC8jmg">
            <targetForm xmi:type="expression:Expression" xmi:id="_DmE4NGwrEe6kvqzAwC8jmg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_JRzhaWwqEe6kvqzAwC8jmg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_JRzhbGwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_MYQ8AGwqEe6kvqzAwC8jmg" name="Do the project" outgoing="_UzPkQGwqEe6kvqzAwC8jmg" incoming="_T4ZsoGwqEe6kvqzAwC8jmg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MYQ8AmwqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MYQ8AWwqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MYQ8A2wqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_MYQ8BGwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_MYQ8BWwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_MYQ8BmwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_MYQ8CGwqEe6kvqzAwC8jmg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_MYQ8B2wqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_MYQ8CmwqEe6kvqzAwC8jmg">
            <targetForm xmi:type="expression:Expression" xmi:id="_DmE4NWwrEe6kvqzAwC8jmg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_MYQ8CWwqEe6kvqzAwC8jmg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_MYQ8DGwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_OSB6AGwqEe6kvqzAwC8jmg" name="Notify project delivery" outgoing="_VKEv4GwqEe6kvqzAwC8jmg" incoming="_UzPkQGwqEe6kvqzAwC8jmg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OSB6AmwqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OSB6AWwqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OSB6A2wqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_OSB6BGwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_OSB6BWwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_OSB6BmwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_OSB6CGwqEe6kvqzAwC8jmg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_OSB6B2wqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_OSB6CmwqEe6kvqzAwC8jmg">
            <targetForm xmi:type="expression:Expression" xmi:id="_DmE4NmwrEe6kvqzAwC8jmg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_OSB6CWwqEe6kvqzAwC8jmg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_OSB6DGwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Q8D3UGwqEe6kvqzAwC8jmg" name="Project finished" incoming="_VKEv4GwqEe6kvqzAwC8jmg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q8D3UmwqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q8D3UWwqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Q8D3U2wqEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_GX8GYGwsEe6kvqzAwC8jmg" name="Proposal approval ?" outgoing="_L7P98GwsEe6kvqzAwC8jmg _P7uJwGwsEe6kvqzAwC8jmg" incoming="__k1s0GwpEe6kvqzAwC8jmg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GX8tcWwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GX8tcGwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GX8tcmwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_MkpgQGwsEe6kvqzAwC8jmg" name="Notify proposal refusal" outgoing="_WlX-UGwsEe6kvqzAwC8jmg" incoming="_P7uJwGwsEe6kvqzAwC8jmg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MkpgQmwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MkpgQWwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MkpgQ2wsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_MkpgRGwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_MkpgRWwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_MkpgRmwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_MkpgSGwsEe6kvqzAwC8jmg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_MkpgR2wsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_MkpgSmwsEe6kvqzAwC8jmg">
            <targetForm xmi:type="expression:Expression" xmi:id="_MkpgS2wsEe6kvqzAwC8jmg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_MkpgSWwsEe6kvqzAwC8jmg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_MkpgTGwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_VCIC4GwsEe6kvqzAwC8jmg" name="Proposal refused" incoming="_WlX-UGwsEe6kvqzAwC8jmg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VCIC4mwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VCIC4WwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VCIC42wsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_c71xIGwsEe6kvqzAwC8jmg" name="Project approval ?" outgoing="_xt5DwGwsEe6kvqzAwC8jmg _zUq0UGwsEe6kvqzAwC8jmg" incoming="_TcVbsGwqEe6kvqzAwC8jmg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_c71xImwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_c71xIWwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_c71xI2wsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_nRkO0GwsEe6kvqzAwC8jmg" name="Notify project refused" outgoing="_w2_Q8GwsEe6kvqzAwC8jmg" incoming="_xt5DwGwsEe6kvqzAwC8jmg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nRkO0WwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nRkO0mwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nRkO02wsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_nRkO1GwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_nRkO1WwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_nRkO1mwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_nRkO12wsEe6kvqzAwC8jmg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_nRkO2GwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_nRkO2WwsEe6kvqzAwC8jmg">
            <targetForm xmi:type="expression:Expression" xmi:id="_nRkO2mwsEe6kvqzAwC8jmg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_nRkO22wsEe6kvqzAwC8jmg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_nRkO3GwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_qkmF0GwsEe6kvqzAwC8jmg" name="Project refused" incoming="_w2_Q8GwsEe6kvqzAwC8jmg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qkmF0WwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qkmF0mwsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qkmF02wsEe6kvqzAwC8jmg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_z7vsNGwQEe6CV7MUNvKj1Q">
        <targetForm xmi:type="expression:Expression" xmi:id="_DmE4N2wrEe6kvqzAwC8jmg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_z7vsNmwQEe6CV7MUNvKj1Q">
        <targetForm xmi:type="expression:Expression" xmi:id="_z7vsN2wQEe6CV7MUNvKj1Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_z7vsOGwQEe6CV7MUNvKj1Q" target="_z7vsJ2wQEe6CV7MUNvKj1Q" source="_z7vsI2wQEe6CV7MUNvKj1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_z7wTMGwQEe6CV7MUNvKj1Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_z7wTMWwQEe6CV7MUNvKj1Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__k1s0GwpEe6kvqzAwC8jmg" target="_GX8GYGwsEe6kvqzAwC8jmg" source="_z7vsJ2wQEe6CV7MUNvKj1Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__k1s0WwpEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="__k1s0mwpEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_S2dugGwqEe6kvqzAwC8jmg" target="_GR3lgGwqEe6kvqzAwC8jmg" source="_z7wJ0GwpEe6kvqzAwC8jmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_S2eVkGwqEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_S2eVkWwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TIwYYGwqEe6kvqzAwC8jmg" target="_H484EGwqEe6kvqzAwC8jmg" source="_GR3lgGwqEe6kvqzAwC8jmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TIwYYWwqEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_TIwYYmwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TcVbsGwqEe6kvqzAwC8jmg" target="_c71xIGwsEe6kvqzAwC8jmg" source="_H484EGwqEe6kvqzAwC8jmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TcVbsWwqEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_TcVbsmwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_T4ZsoGwqEe6kvqzAwC8jmg" target="_MYQ8AGwqEe6kvqzAwC8jmg" source="_JRzhYGwqEe6kvqzAwC8jmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_T4ZsoWwqEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_T4ZsomwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UzPkQGwqEe6kvqzAwC8jmg" target="_OSB6AGwqEe6kvqzAwC8jmg" source="_MYQ8AGwqEe6kvqzAwC8jmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UzPkQWwqEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_UzPkQmwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VKEv4GwqEe6kvqzAwC8jmg" target="_Q8D3UGwqEe6kvqzAwC8jmg" source="_OSB6AGwqEe6kvqzAwC8jmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VKEv4WwqEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_VKEv4mwqEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_L7P98GwsEe6kvqzAwC8jmg" target="_z7wJ0GwpEe6kvqzAwC8jmg" source="_GX8GYGwsEe6kvqzAwC8jmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_L7QlAGwsEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_L7QlAWwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_P7uJwGwsEe6kvqzAwC8jmg" target="_MkpgQGwsEe6kvqzAwC8jmg" source="_GX8GYGwsEe6kvqzAwC8jmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_P7uJwWwsEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_P7uJwmwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WlX-UGwsEe6kvqzAwC8jmg" target="_VCIC4GwsEe6kvqzAwC8jmg" source="_MkpgQGwsEe6kvqzAwC8jmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WlX-UWwsEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_WlX-UmwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_w2_Q8GwsEe6kvqzAwC8jmg" target="_qkmF0GwsEe6kvqzAwC8jmg" source="_nRkO0GwsEe6kvqzAwC8jmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_w2_Q8WwsEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_w2_4AGwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xt5DwGwsEe6kvqzAwC8jmg" target="_nRkO0GwsEe6kvqzAwC8jmg" source="_c71xIGwsEe6kvqzAwC8jmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xt5DwWwsEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_xt5DwmwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zUq0UGwsEe6kvqzAwC8jmg" target="_JRzhYGwqEe6kvqzAwC8jmg" source="_c71xIGwsEe6kvqzAwC8jmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zUq0UWwsEe6kvqzAwC8jmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_zUq0UmwsEe6kvqzAwC8jmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_z7wTMmwQEe6CV7MUNvKj1Q" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_z7wTM2wQEe6CV7MUNvKj1Q"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_z7wTNGwQEe6CV7MUNvKj1Q">
        <name xmi:type="expression:Expression" xmi:id="_z7wTNWwQEe6CV7MUNvKj1Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_z7wTNmwQEe6CV7MUNvKj1Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_z7wTN2wQEe6CV7MUNvKj1Q">
        <name xmi:type="expression:Expression" xmi:id="_z7wTOGwQEe6CV7MUNvKj1Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_z7wTOWwQEe6CV7MUNvKj1Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_z7wTOmwQEe6CV7MUNvKj1Q">
        <name xmi:type="expression:Expression" xmi:id="_z7wTO2wQEe6CV7MUNvKj1Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_z7wTPGwQEe6CV7MUNvKj1Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_z7wTPWwQEe6CV7MUNvKj1Q">
        <name xmi:type="expression:Expression" xmi:id="_z7wTPmwQEe6CV7MUNvKj1Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_z7wTP2wQEe6CV7MUNvKj1Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_z7wTQGwQEe6CV7MUNvKj1Q">
        <name xmi:type="expression:Expression" xmi:id="_z7wTQWwQEe6CV7MUNvKj1Q" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_z7wTQmwQEe6CV7MUNvKj1Q" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_z7wTQ2wQEe6CV7MUNvKj1Q" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_z7wTRGwQEe6CV7MUNvKj1Q" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_z7wTRWwQEe6CV7MUNvKj1Q" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_z7wTRmwQEe6CV7MUNvKj1Q" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_z7wTR2wQEe6CV7MUNvKj1Q" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_z7wTSGwQEe6CV7MUNvKj1Q" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_z7wTSWwQEe6CV7MUNvKj1Q" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_z7wTSmwQEe6CV7MUNvKj1Q" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_z7wTS2wQEe6CV7MUNvKj1Q" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_z7wTTGwQEe6CV7MUNvKj1Q" type="Process" element="_z7vsIGwQEe6CV7MUNvKj1Q" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_z7wTTWwQEe6CV7MUNvKj1Q" type="2007" element="_z7vsIWwQEe6CV7MUNvKj1Q">
      <children xmi:type="notation:DecorationNode" xmi:id="_z7wTTmwQEe6CV7MUNvKj1Q" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_z7wTT2wQEe6CV7MUNvKj1Q" type="7001">
        <children xmi:type="notation:Node" xmi:id="_z7wTUGwQEe6CV7MUNvKj1Q" type="3007" element="_z7vsImwQEe6CV7MUNvKj1Q">
          <children xmi:type="notation:DecorationNode" xmi:id="_z7wTUWwQEe6CV7MUNvKj1Q" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_z7wTUmwQEe6CV7MUNvKj1Q" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_z7wTU2wQEe6CV7MUNvKj1Q" type="3005" element="_z7vsJ2wQEe6CV7MUNvKj1Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_z7wTVGwQEe6CV7MUNvKj1Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_z7wTVWwQEe6CV7MUNvKj1Q" x="158" y="54" width="148" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_z7wTVmwQEe6CV7MUNvKj1Q" type="3002" element="_z7vsI2wQEe6CV7MUNvKj1Q" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_z7wTV2wQEe6CV7MUNvKj1Q" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_z7wTWGwQEe6CV7MUNvKj1Q" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_z7wTWWwQEe6CV7MUNvKj1Q" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_z8M1wGwpEe6kvqzAwC8jmg" type="3005" element="_z7wJ0GwpEe6kvqzAwC8jmg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_z8M1wmwpEe6kvqzAwC8jmg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_z8M1wWwpEe6kvqzAwC8jmg" x="398" y="52" width="153" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GR4zoGwqEe6kvqzAwC8jmg" type="3005" element="_GR3lgGwqEe6kvqzAwC8jmg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_GR4zomwqEe6kvqzAwC8jmg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GR4zoWwqEe6kvqzAwC8jmg" x="566" y="54" width="147" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_H49fJmwqEe6kvqzAwC8jmg" type="3005" element="_H484EGwqEe6kvqzAwC8jmg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_H49fKGwqEe6kvqzAwC8jmg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_H49fJ2wqEe6kvqzAwC8jmg" x="782" y="54" width="150" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JR0IcGwqEe6kvqzAwC8jmg" type="3005" element="_JRzhYGwqEe6kvqzAwC8jmg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_JR0IcmwqEe6kvqzAwC8jmg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JR0IcWwqEe6kvqzAwC8jmg" x="1046" y="53" width="153" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_MYQ8DWwqEe6kvqzAwC8jmg" type="3005" element="_MYQ8AGwqEe6kvqzAwC8jmg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_MYRjEGwqEe6kvqzAwC8jmg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MYQ8DmwqEe6kvqzAwC8jmg" x="1255" y="53" width="152" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OSChEGwqEe6kvqzAwC8jmg" type="3005" element="_OSB6AGwqEe6kvqzAwC8jmg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OSChEmwqEe6kvqzAwC8jmg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OSChEWwqEe6kvqzAwC8jmg" x="1471" y="53" width="153" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Q8EeYGwqEe6kvqzAwC8jmg" type="3003" element="_Q8D3UGwqEe6kvqzAwC8jmg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Q8FFcGwqEe6kvqzAwC8jmg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Q8FFcWwqEe6kvqzAwC8jmg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q8EeYWwqEe6kvqzAwC8jmg" x="1687" y="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GX8tc2wsEe6kvqzAwC8jmg" type="3008" element="_GX8GYGwsEe6kvqzAwC8jmg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_GX8tdWwsEe6kvqzAwC8jmg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_GX8tdmwsEe6kvqzAwC8jmg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GX8tdGwsEe6kvqzAwC8jmg" x="326" y="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_MkqHUGwsEe6kvqzAwC8jmg" type="3005" element="_MkpgQGwsEe6kvqzAwC8jmg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_MkqHUmwsEe6kvqzAwC8jmg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MkqHUWwsEe6kvqzAwC8jmg" x="398" y="162" width="159" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VCIC5GwsEe6kvqzAwC8jmg" type="3003" element="_VCIC4GwsEe6kvqzAwC8jmg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_VCIC5mwsEe6kvqzAwC8jmg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_VCIC52wsEe6kvqzAwC8jmg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VCIC5WwsEe6kvqzAwC8jmg" x="633" y="179"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_c71xJGwsEe6kvqzAwC8jmg" type="3008" element="_c71xIGwsEe6kvqzAwC8jmg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_c72YMGwsEe6kvqzAwC8jmg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_c72YMWwsEe6kvqzAwC8jmg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_c71xJWwsEe6kvqzAwC8jmg" x="974" y="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nRk14GwsEe6kvqzAwC8jmg" type="3005" element="_nRkO0GwsEe6kvqzAwC8jmg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nRk14WwsEe6kvqzAwC8jmg" type="5005" element="_nRkO0GwsEe6kvqzAwC8jmg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nRk14mwsEe6kvqzAwC8jmg" x="1046" y="186" width="153" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qkmF1GwsEe6kvqzAwC8jmg" type="3003" element="_qkmF0GwsEe6kvqzAwC8jmg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qkmF1WwsEe6kvqzAwC8jmg" type="5025" element="_qkmF0GwsEe6kvqzAwC8jmg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qkmF1mwsEe6kvqzAwC8jmg" x="-4" y="15"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qkmF12wsEe6kvqzAwC8jmg" x="1284" y="209"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_z7wTWmwQEe6CV7MUNvKj1Q"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_z7wTW2wQEe6CV7MUNvKj1Q" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_z7wTXGwQEe6CV7MUNvKj1Q"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_z7wTXWwQEe6CV7MUNvKj1Q"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_z7wTXmwQEe6CV7MUNvKj1Q"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_z7wTX2wQEe6CV7MUNvKj1Q"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_z7wTYGwQEe6CV7MUNvKj1Q" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_z7wTYWwQEe6CV7MUNvKj1Q"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_z7wTYmwQEe6CV7MUNvKj1Q"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_z7wTY2wQEe6CV7MUNvKj1Q" width="1855" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_z7wTZGwQEe6CV7MUNvKj1Q"/>
    <edges xmi:type="notation:Connector" xmi:id="_z7wTZWwQEe6CV7MUNvKj1Q" type="4001" element="_z7vsOGwQEe6CV7MUNvKj1Q" source="_z7wTVmwQEe6CV7MUNvKj1Q" target="_z7wTU2wQEe6CV7MUNvKj1Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_z7wTZmwQEe6CV7MUNvKj1Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_z7wTZ2wQEe6CV7MUNvKj1Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_z7wTaGwQEe6CV7MUNvKj1Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_z7wTaWwQEe6CV7MUNvKj1Q" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uHzYwGwqEe6kvqzAwC8jmg" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uHz_0GwqEe6kvqzAwC8jmg" id="(0.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__k1s02wpEe6kvqzAwC8jmg" type="4001" element="__k1s0GwpEe6kvqzAwC8jmg" source="_z7wTU2wQEe6CV7MUNvKj1Q" target="_GX8tc2wsEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__k1s1mwpEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__k1s12wpEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__k1s1GwpEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__k1s1WwpEe6kvqzAwC8jmg" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__k1s2GwpEe6kvqzAwC8jmg" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__k1s2WwpEe6kvqzAwC8jmg" id="(0.09302325581395349,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_S2eVkmwqEe6kvqzAwC8jmg" type="4001" element="_S2dugGwqEe6kvqzAwC8jmg" source="_z8M1wGwpEe6kvqzAwC8jmg" target="_GR4zoGwqEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_S2eVlWwqEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_S2eVlmwqEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_S2eVk2wqEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_S2eVlGwqEe6kvqzAwC8jmg" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S2fjsGwqEe6kvqzAwC8jmg" id="(1.0,0.4935064935064935)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oqATUGwqEe6kvqzAwC8jmg" id="(0.0,0.4931506849315068)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TIwYY2wqEe6kvqzAwC8jmg" type="4001" element="_TIwYYGwqEe6kvqzAwC8jmg" source="_GR4zoGwqEe6kvqzAwC8jmg" target="_H49fJmwqEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TIw_cGwqEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TIw_cWwqEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TIwYZGwqEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TIwYZWwqEe6kvqzAwC8jmg" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TIxmgGwqEe6kvqzAwC8jmg" id="(1.0,0.4931506849315068)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TIxmgWwqEe6kvqzAwC8jmg" id="(0.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TcWCwGwqEe6kvqzAwC8jmg" type="4001" element="_TcVbsGwqEe6kvqzAwC8jmg" source="_H49fJmwqEe6kvqzAwC8jmg" target="_c71xJGwsEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TcWCw2wqEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TcWCxGwqEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TcWCwWwqEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TcWCwmwqEe6kvqzAwC8jmg" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_TcWp0GwqEe6kvqzAwC8jmg" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oqATUmwqEe6kvqzAwC8jmg" id="(0.06976744186046512,0.5348837209302325)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_T4aTsGwqEe6kvqzAwC8jmg" type="4001" element="_T4ZsoGwqEe6kvqzAwC8jmg" source="_JR0IcGwqEe6kvqzAwC8jmg" target="_MYQ8DWwqEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_T4aTs2wqEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_T4aTtGwqEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_T4aTsWwqEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_T4aTsmwqEe6kvqzAwC8jmg" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_T4bh0GwqEe6kvqzAwC8jmg" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oqATUWwqEe6kvqzAwC8jmg" id="(0.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UzPkQ2wqEe6kvqzAwC8jmg" type="4001" element="_UzPkQGwqEe6kvqzAwC8jmg" source="_MYQ8DWwqEe6kvqzAwC8jmg" target="_OSChEGwqEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UzQLUGwqEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UzQLUWwqEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UzPkRGwqEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UzPkRWwqEe6kvqzAwC8jmg" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UzQyYGwqEe6kvqzAwC8jmg" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_op_sQGwqEe6kvqzAwC8jmg" id="(0.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VKFW8GwqEe6kvqzAwC8jmg" type="4001" element="_VKEv4GwqEe6kvqzAwC8jmg" source="_OSChEGwqEe6kvqzAwC8jmg" target="_Q8EeYGwqEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VKF-AGwqEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VKF-AWwqEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VKFW8WwqEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VKFW8mwqEe6kvqzAwC8jmg" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VKHzMGwqEe6kvqzAwC8jmg" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uH0m4GwqEe6kvqzAwC8jmg" id="(0.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_L7RMEGwsEe6kvqzAwC8jmg" type="4001" element="_L7P98GwsEe6kvqzAwC8jmg" source="_GX8tc2wsEe6kvqzAwC8jmg" target="_z8M1wGwpEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_L7RME2wsEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_L7RMFGwsEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_L7RMEWwsEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_L7RMEmwsEe6kvqzAwC8jmg" points="[-14, -18, -29, 49]$[15, -67, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_L7SaMGwsEe6kvqzAwC8jmg" id="(0.46511627906976744,0.09302325581395349)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_L7SaMWwsEe6kvqzAwC8jmg" id="(0.0,0.5324675324675324)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_P74h0GwsEe6kvqzAwC8jmg" type="4001" element="_P7uJwGwsEe6kvqzAwC8jmg" source="_GX8tc2wsEe6kvqzAwC8jmg" target="_MkqHUGwsEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_P75I4GwsEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_P75I4WwsEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_P74h0WwsEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_P74h0mwsEe6kvqzAwC8jmg" points="[-3, -3, -77, -110]$[74, 107, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_P75v8GwsEe6kvqzAwC8jmg" id="(0.46511627906976744,0.9302325581395349)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_P75v8WwsEe6kvqzAwC8jmg" id="(0.0,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WlX-U2wsEe6kvqzAwC8jmg" type="4001" element="_WlX-UGwsEe6kvqzAwC8jmg" source="_MkqHUGwsEe6kvqzAwC8jmg" target="_VCIC5GwsEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WlYlYGwsEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WlYlYWwsEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WlX-VGwsEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WlX-VWwsEe6kvqzAwC8jmg" points="[0, 0, -73, -23]$[71, 23, -2, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WlZMcGwsEe6kvqzAwC8jmg" id="(1.0,0.37349397590361444)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WlZMcWwsEe6kvqzAwC8jmg" id="(0.06666666666666667,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_w2_4AWwsEe6kvqzAwC8jmg" type="4001" element="_w2_Q8GwsEe6kvqzAwC8jmg" source="_nRk14GwsEe6kvqzAwC8jmg" target="_qkmF1GwsEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_w2_4BGwsEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_w2_4BWwsEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_w2_4AmwsEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_w2_4A2wsEe6kvqzAwC8jmg" points="[0, 8, -100, 1]$[101, 21, 1, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_w3AfEGwsEe6kvqzAwC8jmg" id="(1.0,0.40789473684210525)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xt5Dw2wsEe6kvqzAwC8jmg" type="4001" element="_xt5DwGwsEe6kvqzAwC8jmg" source="_c71xJGwsEe6kvqzAwC8jmg" target="_nRk14GwsEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xt5q0GwsEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xt5q0WwsEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xt5DxGwsEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xt5DxWwsEe6kvqzAwC8jmg" points="[-4, -4, -147, -126]$[133, 121, -10, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xt6R4GwsEe6kvqzAwC8jmg" id="(0.4418604651162791,0.8372093023255814)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xt6R4WwsEe6kvqzAwC8jmg" id="(0.06535947712418301,0.47368421052631576)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zUwT4GwsEe6kvqzAwC8jmg" type="4001" element="_zUq0UGwsEe6kvqzAwC8jmg" source="_c71xJGwsEe6kvqzAwC8jmg" target="_JR0IcGwqEe6kvqzAwC8jmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zUwT42wsEe6kvqzAwC8jmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zUwT5GwsEe6kvqzAwC8jmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zUwT4WwsEe6kvqzAwC8jmg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zUwT4mwsEe6kvqzAwC8jmg" points="[-14, -21, -35, 58]$[6, -79, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zUxiAGwsEe6kvqzAwC8jmg" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zUxiAWwsEe6kvqzAwC8jmg" id="(0.0196078431372549,0.39473684210526316)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
